flowchart LR

Frontend -->|REST Request| Express
Browser -->|Attach JWT Cookie| Express

Express --> JWTMiddleware["JWT Middleware"]
JWTMiddleware -->|Valid| Controller["API Controller"]
JWTMiddleware -->|Invalid| Unauthorized["401 Unauthorized"]

Controller --> Prisma
Prisma --> SQLite
